### ISSUE TITLE
Updated pip package

### ISSUE THREAD

**Issue by janreising** [apasarkar/jnormcorre#3]
Hi, 
I am using this package in my analysis pipeline and the current version available through pip hasn't got the fix `np.int` to `int` yet. Would it be possible to update the package to include those changes? Thanks in advance!

**Comment by apasarkar** [comment]
Hi @janreising thanks for checking out the package! I will update the package on PyPI and get back to you here.

**Comment by janreising** [comment]
Hi @apasarkar, thanks a lot for the quick turnaround on this. I really appreciate it! I did some testing with the current version and ran into some small problems, and just created a pull request (#4) that address my issues. Hopefully the changes will be helpful for everybody else as well.

**Comment by apasarkar** [comment]
Thanks for the fantastic contributions @janreising  -- I will dig into this asap and get back to you.

**Comment by janreising** [comment]
Hi @apasarkar, 

Your module is a vital component in my pipeline; it really brings everything together and enhances the functionality substantially.  Currently, I've got a workaround where users pull my updated branch from GitHub directly, but that's not gonna work once I publish my pipeline as a pip package. Since I am getting ready to resubmit my paper where I describe my package, it would be amazing to have a smooth pip installation process in the instructions.

I was wondering if / when you are planning to include the PR. I totally get that we're all swamped, so if it seems like the merge might take a while, no worries at all! I can definitely explore other solutions or include the workaround in the installation guide. Just wanted to check in and see how feasible it would be to get the PR included before I resubmit. Thanks a ton for your time, and no rush at all.

**Comment by apasarkar** [comment]
Hi @janreising thanks for following up. This is actually perfect timing, I've just wrapped up a submission of my own and was planning on plugging back into your PR fully today. I'll get back to you today with any questions/thoughts and we can aim to have the updates completed in the coming day(s).

**Comment by apasarkar** [comment]
Hi @janreising I've resolved the remaining bugs, merged the pull requests to main, and published a new version of the package (0.0.7). Let me know if this works for your use case -- happy to help with anything else needed on this front.

**Comment by janreising** [comment]
Perfect! Thanks a lot for your work. I spend the day testing and everything works smoothly now.
