### ISSUE TITLE
running the demo with a new file

### ISSUE THREAD

**Issue by ZeitgeberH** [apasarkar/jnormcorre#6]
It is strange that it fails in the middle. My image stack dimension is (32, 64, 160376).

`obj, registered_filename = motion_correct(filename, ".", sketch_template = True, pw_rigid = True, save_movie=True, overlaps=(10,10))`

'Running motion correction...'

'Number of chunks is 802'

100%|██████████| 5/5 [00:49<00:00,  9.96s/it]

this motion correction step took 49.81373691558838

100%|██████████| 5/5 [00:47<00:00,  9.55s/it]

this motion correction step took 47.76651620864868

100%|██████████| 5/5 [00:47<00:00,  9.53s/it]

this motion correction step took 47.669782400131226

100%|██████████| 5/5 [00:47<00:00,  9.54s/it]

this motion correction step took 47.68355441093445

  0%|          | 0/802 [00:05<?, ?it/s]

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[6], line 1
----> 1 obj, registered_filename = motion_correct(filename, ".", sketch_template = True, pw_rigid = True, save_movie=True, overlaps=(10,10))

Cell In[5], line 134, in motion_correct(filename, outdir, dxy, max_shift_um, max_deviation_rigid, patch_motion_um, overlaps, border_nan, niter_rig, splits, pw_rigid, gSig_filt, save_movie, dtype, sketch_template, **params)
    131 corrector = motion_correction.MotionCorrect(target, **mc_dict)
    133 # Run MC, Always Saving Non-Final Outputs For Use In Next Iteration
--> 134 corrector_obj, target_file = corrector.motion_correct(
    135     save_movie=save_movie
    136 )
    138 display("Motion correction completed.")
    140 # Save Frame-wise Shifts

File /opt/conda/lib/python3.8/site-packages/jnormcorre/motion_correction.py:459, in MotionCorrect.motion_correct(self, template, save_movie)
    453         self.min_mov = np.array([high_pass_filter_cv(m_, self.filter_kernel)
    454             for m_ in movies.load(self.fname[0], var_name_hdf5=self.var_name_hdf5,
    455                               subindices=slice(400))]).min()
    458 if self.pw_rigid:
--> 459     self.motion_correct_pwrigid(template=template, save_movie=save_movie)
    460     b0 = np.ceil(np.maximum(np.max(np.abs(self.x_shifts_els)),
    461                             np.max(np.abs(self.y_shifts_els))))
    462 else:

File /opt/conda/lib/python3.8/site-packages/jnormcorre/motion_correction.py:563, in MotionCorrect.motion_correct_pwrigid(self, save_movie, template, show_template)
    560 self.coord_shifts_els:List = []
    561 for name_cur in self.fname:
    562     _fname_tot_els, new_template_els, _templates_els,\
--> 563         _x_shifts_els, _y_shifts_els, _z_shifts_els, _coord_shifts_els = motion_correct_batch_pwrigid(
    564             name_cur, self.max_shifts, self.strides, self.overlaps, -self.min_mov,
    565             upsample_factor_grid=self.upsample_factor_grid,
    566             max_deviation_rigid=self.max_deviation_rigid, splits=self.splits_els,
    567             num_splits_to_process=self.num_splits_to_process_els, num_iter=num_iter, template=self.total_template_els,
    568             save_movie=save_movie, nonneg_movie=self.nonneg_movie, var_name_hdf5=self.var_name_hdf5,
    569             indices=self.indices, filter_kernel=self.filter_kernel, bigtiff=self.bigtiff)
    571     if show_template:
    572         pl.imshow(new_template_els)

File /opt/conda/lib/python3.8/site-packages/jnormcorre/motion_correction.py:2498, in motion_correct_batch_pwrigid(fname, max_shifts, strides, overlaps, add_to_movie, newoverlaps, newstrides, upsample_factor_grid, max_deviation_rigid, splits, num_splits_to_process, num_iter, template, save_movie, nonneg_movie, var_name_hdf5, indices, filter_kernel, bigtiff)
   2496 if iter_ == num_iter - 1 and save_flag:
   2497     num_splits_to_process = None
-> 2498 fname_tot_els, res_el = motion_correction_piecewise(fname, splits, strides, overlaps,
   2499                                                     add_to_movie=add_to_movie, template=old_templ, max_shifts=max_shifts,
   2500                                                     max_deviation_rigid=max_deviation_rigid,
   2501                                                     newoverlaps=newoverlaps, newstrides=newstrides,
   2502                                                     upsample_factor_grid=upsample_factor_grid, order='F', save_movie=save_flag,
   2503                                                     base_name=base_name, num_splits=num_splits_to_process,
   2504                                                     nonneg_movie=nonneg_movie, var_name_hdf5=var_name_hdf5,
   2505                                                     indices=indices, filter_kernel=filter_kernel, bigtiff=bigtiff)
   2507 new_templ = np.nanmedian(np.dstack([r[-1] for r in res_el]), -1)
   2508 if filter_kernel is not None:

File /opt/conda/lib/python3.8/site-packages/jnormcorre/motion_correction.py:2756, in motion_correction_piecewise(fname, splits, strides, overlaps, add_to_movie, template, max_shifts, max_deviation_rigid, newoverlaps, newstrides, upsample_factor_grid, order, save_movie, base_name, subidx, num_splits, nonneg_movie, var_name_hdf5, indices, filter_kernel, bigtiff)
   2754 start_time = time.time()
   2755 split_constant = load_split_heuristic(dims[0], dims[1], T)
-> 2756 res = tile_and_correct_dataloader(pars, split_constant=split_constant, bigtiff=bigtiff)
   2757 print("this motion correction step took {}".format(time.time() - start_time))
   2758 return fname_tot, res

File /opt/conda/lib/python3.8/site-packages/jnormcorre/motion_correction.py:2643, in tile_and_correct_dataloader(param_list, split_constant, bigtiff)
   2641 else:
   2642     if filter_kernel is None:
-> 2643         outs = tile_and_correct_pwrigid_vmap(imgs, template, strides[0], strides[1], overlaps[0], overlaps[1], \
   2644                                                                            max_shifts,upsample_factor_fft, max_deviation_rigid, add_to_movie)
   2645     else:
   2646         imgs_filtered = high_pass_batch(filter_kernel, imgs)

    [... skipping hidden 15 frame]

File /opt/conda/lib/python3.8/site-packages/jnormcorre/motion_correction.py:2210, in tile_and_correct_ideal(img, template, strides_0, strides_1, overlaps_0, overlaps_1, max_shifts, upsample_factor_fft, max_deviation_rigid, add_to_movie)
   2205 rigid_shts, sfr_freq, diffphase = register_translation_jax_simple(
   2206     img, template, upsample_factor=upsample_factor_fft, max_shifts=max_shifts)
   2208 # extract patches
-> 2210 templates = get_patches_jax(template, overlaps[0], overlaps[1], strides[0], strides[1])
   2211 xy_grid = get_xy_grid(template, overlaps[0], overlaps[1], strides[0], strides[1])
   2212 imgs = get_patches_jax(img, overlaps[0], overlaps[1], strides[0], strides[1])

File /opt/conda/lib/python3.8/site-packages/jnormcorre/motion_correction.py:1899, in get_patches_jax(img, overlaps_0, overlaps_1, strides_0, strides_1)
   1897 first_dim_new = product[:, 0]
   1898 second_dim_new = product[:, 1]
-> 1899 return crop_image_vmap(img, first_dim_new, second_dim_new, overlaps_0+strides_0, overlaps_1+strides_1)

    [... skipping hidden 15 frame]

File /opt/conda/lib/python3.8/site-packages/jnormcorre/motion_correction.py:1887, in crop_image(img, x, y, length_1, length_2)
   1885 @partial(jit, static_argnums=(3,4))
   1886 def crop_image(img, x, y, length_1, length_2):
-> 1887     out = jax.lax.dynamic_slice(img, (x,y), (length_1, length_2))
   1888     return out

    [... skipping hidden 8 frame]

File /opt/conda/lib/python3.8/site-packages/jax/_src/lax/slicing.py:843, in _dynamic_slice_shape_rule(operand, slice_sizes, *start_indices)
    840 if not core.greater_equal_shape(operand.shape, slice_sizes):
    841   msg = ("slice slice_sizes must be less than or equal to operand shape, "
    842          "got slice_sizes {} for operand shape {}.")
--> 843   raise TypeError(msg.format(slice_sizes, operand.shape))
    844 if not all(core.greater_equal_dim(ssz, 0) for ssz in slice_sizes):
    845   msg = ("slice slice_sizes must be greater than or equal to zero, "
    846          "got slice_sizes of {}.")

TypeError: slice slice_sizes must be less than or equal to operand shape, got slice_sizes (60, 60) for operand shape (32, 64).

**Comment by apasarkar** [comment]
Thanks @ZeitgeberH! I will look into this and get back to you asap.

**Comment by ZeitgeberH** [comment]
Hi @apasarkar, I rerun it with a new set of parameters consistent with my image stack. It works fine.
`overlaps = (4,4)
max_shift_um = (3.0,3.0)
patch_motion_um = (1., 1.)`

The results looks great! Good work!

**Comment by apasarkar** [comment]
@ZeitgeberH Just noting that the updated demo notebook now includes a lot more documentation for each parameter used in this function. The core code actually includes more checks (to explicitly prevent the error you were running into, where the overlaps were too large). The demo now shows how to pick a value for overlaps that is definitely smaller than the "stride" parameter to avoid the bug above (we enforce this so that when doing piecewise rigid registration, each pixel of the movie contains at most 2 overlapping tiles). The demo notebook also shows how to pick the parameters by thinking in 3D space (pixels, microns, etc.) and also in pixel space (number of pixels in the stride, overlap, etc.). Planning to publish more documentation shortly.
